# Generated by Django 4.2.1 on 2024-05-20 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0002_alter_user_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_photo',
        ),
    ]
